/**
 * The demo's local store.
 *
 * One JSON document in AsyncStorage, loaded once and written back after each change, so a demo
 * survives being backgrounded, killed and reopened -- which matters when the point is to hand a
 * phone to someone else. Nothing in it leaves the device, and every value in it was generated by
 * this build.
 */

import AsyncStorage from "@react-native-async-storage/async-storage";

import { logMobileError, runInBackground } from "../observability";
import { seedTables } from "./seed";
import { DEMO_TABLES, emptyTables, type DemoRow, type DemoTables } from "./types";

const STORAGE_KEY = "relay.demo.tables.v1";
const WRITE_DELAY_MS = 300;

function isTableDocument(value: unknown): value is DemoTables {
  if (typeof value !== "object" || value === null) return false;
  const record = value as Record<string, unknown>;
  return DEMO_TABLES.every((table) => record[table] === undefined || Array.isArray(record[table]));
}

class DemoDatabase {
  private tables: DemoTables = emptyTables();
  private loading: Promise<void> | undefined;
  private write: ReturnType<typeof setTimeout> | undefined;

  /**
   * Resolves once the stored document has been read, or seeded when there is none.
   *
   * Every query awaits this. The Supabase client is constructed synchronously by the auth provider,
   * so the load cannot happen there, and reading a half-empty store would show an empty inbox for
   * one frame before the real one replaced it.
   */
  ready(): Promise<void> {
    this.loading ??= this.load();
    return this.loading;
  }

  rows(table: string): DemoRow[] {
    return (this.tables[table] ??= []);
  }

  /** The live document, for a write that spans several tables at once such as a capture. */
  document(): DemoTables {
    return this.tables;
  }

  replace(table: string, rows: DemoRow[]): void {
    this.tables[table] = rows;
  }

  /** Called after any mutation. Writes are coalesced: a burst of captures is one store write. */
  touch(): void {
    if (this.write !== undefined) clearTimeout(this.write);
    this.write = setTimeout(() => {
      this.write = undefined;
      runInBackground(this.save(), "demo.store_write_failed", {
        code: "DEMO_STORE_WRITE_FAILED",
        integration: "async-storage",
        operation: "setItem",
      });
    }, WRITE_DELAY_MS);
  }

  async reset(): Promise<void> {
    this.tables = seedTables();
    this.loading = Promise.resolve();
    await this.save();
  }

  private async save(): Promise<void> {
    await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(this.tables));
  }

  private async load(): Promise<void> {
    let stored: string | null = null;
    try {
      stored = await AsyncStorage.getItem(STORAGE_KEY);
    } catch (error: unknown) {
      // A store that cannot be read is not a failed demo: it is seeded instead, and the reason is
      // recorded once here rather than surfacing as an unexplained empty account.
      logMobileError("demo.store_read_failed", error, {
        code: "DEMO_STORE_READ_FAILED",
        integration: "async-storage",
        operation: "getItem",
      });
    }

    if (stored !== null) {
      try {
        const parsed: unknown = JSON.parse(stored);
        if (isTableDocument(parsed)) {
          this.tables = { ...emptyTables(), ...parsed };
          return;
        }
      } catch (error: unknown) {
        logMobileError("demo.store_document_invalid", error, {
          code: "DEMO_STORE_DOCUMENT_INVALID",
          integration: "async-storage",
          operation: "parse",
        });
      }
    }

    this.tables = seedTables();
    await this.save();
  }
}

export const demoDatabase = new DemoDatabase();
