/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=development --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.generated.d.ts` (hash: 3cb80ac9fae754d43a21aab2f6e5b00d)
interface __BaseEnv_CloudflareEnv {
	NEXTJS_ENV: "production";
	RELAY_INGEST_SHARED_SECRET: string;
	WORKER_SELF_REFERENCE: Fetcher /* relay-api-development */;
	PIPELINE: Fetcher /* relay-pipeline-development */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV" | "RELAY_INGEST_SHARED_SECRET">> {}
}
