/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.generated.d.ts` (hash: 794a20bb33486d973ede33defeb92674)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	NEXTJS_ENV: "production";
	RELAY_ENVIRONMENT: "production";
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GOOGLE_PUBSUB_AUDIENCE: string;
	GOOGLE_PUBSUB_SERVICE_ACCOUNT_EMAIL: string;
	RELAY_CREDENTIAL_KEK_KEYRING: string;
	RELAY_INGEST_SHARED_SECRET: string;
	RELAY_RECOVERY_SHARED_SECRET: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
	SUPABASE_URL: string;
	WORKER_SELF_REFERENCE: Fetcher /* relay-api-production */;
	PIPELINE: Fetcher /* relay-pipeline-production */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV" | "RELAY_ENVIRONMENT" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "GOOGLE_PUBSUB_AUDIENCE" | "GOOGLE_PUBSUB_SERVICE_ACCOUNT_EMAIL" | "RELAY_CREDENTIAL_KEK_KEYRING" | "RELAY_INGEST_SHARED_SECRET" | "RELAY_RECOVERY_SHARED_SECRET" | "SUPABASE_SERVICE_ROLE_KEY" | "SUPABASE_URL">> {}
}
