/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.generated.d.ts` (hash: 2b43b3182723018041993ad0a6b412d4)
interface __BaseEnv_CloudflareEnv {
	ASSETS: Fetcher;
	NEXTJS_ENV: "production";
	RELAY_INGEST_SHARED_SECRET: string;
	WORKER_SELF_REFERENCE: Fetcher /* relay-api-production */;
	PIPELINE: Fetcher /* relay-pipeline-production */;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXTJS_ENV" | "RELAY_INGEST_SHARED_SECRET">> {}
}
